version: '3'
pipeline:

  build:
    image: node:8.1.2-alpine
    environment:
      - SE=${TEST}
    commands:
      - echo "heia"
      #- npm install webpack -g
      #- npm install
      #- npm build
    # Only build on master
    bundle:
      when:
        branch: master  
      
      
  publish:
    image: plugins/docker
    registry: registry.sindrenerdal.no:5000
    repo: registry.sindrenerdal.no:5000/hextorgb
    tag: latest
    #insecure: false    
    secrets: [ REGISTRY_USERNAME, REGISTRY_PASSWORD ]
  #deploy:
    #image: nginx:alpine
    #container_name: nginx-hextorgb
    #ports:
      #- "80:80"
    #commands:
      #- cp -a build/. /usr/share/nginx/html/
    # Only deploy on master
    #bundle:
     # when:
       # branch: master 

