version: '3'
pipeline:
  build:
    image: node:8.1.2-alpine
    commands:
      - npm install webpack -g
      - npm install
      - npm build
      - ls build/


  deploy:
    image: nginx:alpine
    container_name: nginx-hextorgb
    ports:
      - "82:80"
    commands:
      - ls
      - cp build/ /usr/share/nginx/html


