version: '3'
pipeline:
  

  deploy:  
    image: ubuntu
    secrets: [SSH_PATH]
    volumes:
      - /etc/deployment:/etc/deployment
    commands:
      - useradd -m -d /home/deployUser deployUser
      - echo "deployUser:deployUser" | chpasswd
      - mkdir -p /home/deployUser/.ssh
      - cp $SSH_PATH /home/deployUser/.ssh/
      - ls -l /home/deployUser/.ssh
      - chmod 600 /home/deployUser/.ssh
      - chown -R deployUser /home/deployUser/.ssh
      - apt-get -yq update && apt-get -yqq install ssh
      - su - deployUser
      - ssh -o StrictHostKeyChecking=no dev@sindrenerdal.no 'echo "heia"'
  #build:
    #dockerfile: Dockerfile.deploy
   # secrets: [SSH_PATH]
    #volumes:
    #  - /etc/deployment:/etc/deployment
    #commands:
      #- apt-get -yq update && apt-get -yqq install ssh
    #  - ls -l
    #  - ls -l /home/
      #- mkdir .ssh
      #- echo $SSH_PATH
      #- cp -a $SSH_PATH .ssh/
      #- ssh -tt dev@sindrenerdal.no
  
  #publish:
  #  image: docker 
  #  privileged: true
   # volumes:
   #   - /var/run/docker.sock:/var/run/docker.sock
  #  environment:
   #   - KEY=${test}
   # commands:
    #  - echo ${TESTER}
    #  - echo ${test}
   #   - docker build --tag registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER} . 
   #   - docker images
    #  - docker push registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER}
   #   - docker rmi registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER}
  
  
  
  #deploy:
    #image: appleboy/drone-ssh
   # host: sindrenerdal.no
  #  username: dev
 #   secrets: [SSH_KEY]
  #  key: $SSH_KEY
   # environment:
   #   - SSH_KEY=${SSH_KEY}
  
  #funker, men ikke auth
  #deploy:
    #image: appleboy/drone-ssh
    #host: sindrenerdal.no
    #username: dev
    #secrets: [SSH_KEY]
    #key: $SSH_KEY
    #environment:
      #- SSH_KEY=${SSH_KEY}
    
    


  #build:
    #image: node:8.1.2-alpine
    #environment: 
      #- SE=${TEST}
    #commands:
     # - echo "heia"
      #- npm install webpack -g
      #- npm install
      #- npm build
    # Only build on master
    #bundle:
     # when:
      # branch: master  
      
      
  
  #deploy:
    #image: nginx:alpine
    #container_name: nginx-hextorgb
    #ports:
      #- "80:80"
    #commands:
      #- cp -a build/. /usr/share/nginx/html/
    # Only deploy on master
    #bundle:
     # when:
       # branch: master  

