version: '3'
pipeline:
  
  build:
    image: alpine
    secrets: [ ssh_key ]
    commands:
      - echo ${test}
  
  publish:
    image: docker 
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - KEY=${test}
    commands: 
      - echo ${test}
      - docker ps -a
      - docker images
      - docker build --tag registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER} . 
      - docker push registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER}
      - docker rmi registry.sindrenerdal.no:5000/hex_to_rgb:${DRONE_BUILD_NUMBER}
  
  deploy:
    secrets: 
      [test]
    image: appleboy/drone-ssh
    host: sindrenerdal.no
    username: dev
    key: $test
    
    


  #build:
    #image: node:8.1.2-alpine
    #environment: 
      #- SE=${TEST}
    #commands:
     # - echo "heia"
      #- npm install webpack -g
      #- npm install
      #- npm build
    # Only build on master
    #bundle:
     # when:
      # branch: master  
      
      
  
  #deploy:
    #image: nginx:alpine
    #container_name: nginx-hextorgb
    #ports:
      #- "80:80"
    #commands:
      #- cp -a build/. /usr/share/nginx/html/
    # Only deploy on master
    #bundle:
     # when:
       # branch: master  

