version: '3'
pipeline:

  build:
    image: node:8.1.2-alpine
    commands:
      - npm install webpack -g
      - npm install
      - npm build
    # Only build on master
    bundle:
      when:
        branch: master
  
  push:
    commands:
      - docker build -t localhost:5000/hex-to-rgb .  
      - docker push localhost:5000/hex-to-rgb  
      
  #deploy:
    #image: nginx:alpine
    #container_name: nginx-hextorgb
    #ports:
      #- "80:80"
    #commands:
      #- cp -a build/. /usr/share/nginx/html/
    # Only deploy on master
    #bundle:
     # when:
       # branch: master

