version: '3'
pipeline:

  build:
    image: node:8.1.2-alpine
    commands:
      - npm install webpack -g
      - npm install
      - npm build
    # Only build on master
    bundle:
      when:
        branch: master

  deploy:
    image: nginx:alpine
    container_name: nginx-hextorgb
    ports:
      - "81:80"
    commands:
      - cp -a build/. /usr/share/nginx/html/
    # Only deploy on master
    bundle:
      when:
        branch: master

